### ISSUE TITLE
Iso to extend Reifiable and be nodes of IR

### ISSUE THREAD

**Issue by aslesarenko** [scalan/scalan#94] opened 2015-08-16 21:00 UTC
Now instances of `Iso[From,To]` are not nodes of IR even though they are used in other nodes e.g. `View[From, To]`, `View1[A,B,C[_]]`.

##### Considerations for implementation

* `Iso` should extend `Reifiable`
* Each Iso instance should have Sym
* Equality of `Iso` should use alpha-quality for `fromFun` and `toFun`
* everywhere in other nodes direct references to `Iso[A,B]` should be replaced to `Exp[Iso[A,B]]` (e.g. Views).
* it is still ok to use `Iso` in local variables and arguments

**Comment by alexeyr** [comment] 2015-12-11 07:06
Duplicate of #138.

**Closed by alexeyr** 2015-12-11 07:06 UTC
Labels: feature, medium priority
